#
#   This application provides a sample application of Shiny to access to a large dataset of 
#   trips generated by the Metropolitan Transportation Commisssion's activity-
#   based travel demand model.  
# 
# 
# 
#

library(shiny)
library(ggplot2)



shinyUI(fluidPage(
    
    # Application title
    titlePanel("Trips by Mode and County"),
    
    # Sidebar with controls to select the counties
    sidebarLayout(
        sidebarPanel(
            p("This app characterizes trips by mode of travel between counties in 
              the San Francisco Bay Area generated by a regional travel demand model."
            ),
            
            selectInput("O", label=h4("County from"), 
                    choices = list("San Francisco"=1, "San Mateo" = 2, "Santa Clara" = 3,
                                   "Alameda"=4, "Contra Costa" = 5, "Solano" = 6, 
                                   "Napa" = 7, "Sonoma" = 8, "Marin" = 9), 
                    selected = 1, 
                    multiple = FALSE, selectize = TRUE),
            br(),
            
            selectInput("D", label=h4("County to"), 
                        choices = list("San Francisco"=1, "San Mateo" = 2, "Santa Clara" = 3,
                                       "Alameda"=4, "Contra Costa" = 5, "Solano" = 6, 
                                       "Napa" = 7, "Sonoma" = 8, "Marin" = 9), 
                        selected = 1, 
                        multiple = FALSE, selectize = TRUE),
            img(src="ui.gif", height=252, width=276)
        ),
        
        # Show a tabset that includes a plot, summary, and table view
        # of the generated distribution
        mainPanel(
            tabsetPanel(type = "tabs", 
                        tabPanel("Plot", plotOutput("plot")), 
                        tabPanel("Table", tableOutput("table")),
                        tabPanel("Data Summary", verbatimTextOutput("summary"))
            )
        )
    )
))

